# Site settings
title: "Pallavi Shastry's Blog"
header-img: img/home-bg.jpg
email: pallavi046@gmail.com
description: "Place to pen down my learnings, just so I remember them for a very long time"
baseurl: ""
twitter_username: pallavi_shastry
github_username:  pallavits
facebook_username:  Pshastry
email_username:  pallavi046@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
